on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH Host Key
        run: ssh-keyscan -p $SSH_PORT $SSH_HOST >> ~/.ssh/known_hosts

      - name: Deploy to Namecheap
        env:
          SSH_HOST: server345.web-hosting.com
          SSH_USER: harbteat
          SSH_PORT: 21098
          DEPLOY_PATH: /home/harbteat/public_html/
        run: |
          rsync -avz -e "ssh -p $SSH_PORT" \
            --delete \
            --exclude '.git' \
            --exclude '.github' \
            . $SSH_USER@$SSH_HOST:$DEPLOY_PATH