name: Deploy to Namecheap

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Deploy to Namecheap
        env:
          SSH_PORT: 21098
        run: |
          # Disable host key checking
          mkdir -p ~/.ssh
          echo "Host *" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          echo "  UserKnownHostsFile /dev/null" >> ~/.ssh/config

          # Add remote repository
          git remote add namecheap "ssh://harbteat@server345.web-hosting.com:$SSH_PORT/home/harbteat/repositories/Harbor-AI-website-claude-v0.1-new"
          
          # Push to remote repository
          git push namecheap main
          
          # Copy files to public_html using SSH
          ssh -p $SSH_PORT harbteat@server345.web-hosting.com "cp -R /home/harbteat/repositories/Harbor-AI-website-claude-v0.1-new/* /home/harbteat/public_html/"