name: Deploy to Namecheap

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Add host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 21098 -H server345.web-hosting.com >> ~/.ssh/known_hosts
      
      - name: Deploy to Namecheap
        run: |
          git remote add namecheap ssh://harbteat@server345.web-hosting.com:21098/home/harbteat/repositories/Harbor-AI-website-claude-v0.1-new
          git push --force namecheap main
      
      - name: Copy to public_html
        uses: appleboy/ssh-action@master
        with:
          host: server345.web-hosting.com
          username: harbteat
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 21098
          script: |
            cp -R /home/harbteat/repositories/Harbor-AI-website-claude-v0.1-new/* /home/harbteat/public_html/