name: Deploy to Namecheap

on:
  push:
    branches: [ main ]  # Adjust if your primary branch has a different name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          
      - name: Deploy to Namecheap
        run: |
          git remote add namecheap ssh://harbteat@server345.web-hosting.com:21098/home/harbteat/repositories/Harbor-AI-website-claude-v0.1-new
          git push namecheap main