name: Deploy to Namecheap

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: replace
      
      - name: Connect to server and deploy
        run: |
          # Push to Git repository
          git remote add namecheap ssh://harbteat@server345.web-hosting.com:21098/home/harbteat/repositories/Harbor-AI-website-claude-v0.1-new
          git push namecheap main
          
          # SSH into server and copy files
          ssh -p 21098 harbteat@server345.web-hosting.com "cp -R /home/harbteat/repositories/Harbor-AI-website-claude-v0.1-new/* /home/harbteat/public_html/"