name: Deploy to Namecheap

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: server345.web-hosting.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 21098
      
      - name: Deploy to Namecheap
        run: |
          git remote add namecheap ssh://harbteat@server345.web-hosting.com:21098/home/harbteat/repositories/Harbor-AI-website-claude-v0.1-new
          git push namecheap main
          
          # Copy files to public_html
          ssh harbteat@server345.web-hosting.com -p 21098 "cp -R /home/harbteat/repositories/Harbor-AI-website-claude-v0.1-new/* /home/harbteat/public_html/"